name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Sync s3
    - uses: jakejarvis/s3-sync-action@main
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ rrs-product-details }}
        AWS_ACCESS_KEY_ID: ${{ AKIASOLGLD6ZA3N3QXGL }}
        AWS_SECRET_ACCESS_KEY: ${{ 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 }}
        AWS_REGION: 'ap-northeast-1'
        SOURCE_DIR: 'public'      # optional: defaults to entire repository
